---
- name: Installer MySQL/MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  notify: Redémarrer MySQL

- name: Install PyMySQL for Python3
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3
  when: ansible_python_version is version('3', '>=')

- name: Install PyMySQL for Python2
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip
  when: ansible_python_version is version('3', '<')

- name: Verify PyMySQL installation
  ansible.builtin.shell: "python{{ ansible_python_version.major }} -c 'import pymysql'"
  changed_when: false

- name: Activer mariadb
  service:
    name: mariadb
    enabled: yes

- name: Configurer le mot de passe root de MySQL
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes

- name: Créer la base de données WordPress
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Créer l'utilisateur de la base de données WordPress
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
