wordpress_download_url: "https://wordpress.org/latest.tar.gz"
wordpress_install_dir: "/var/www/html/wordpress"
wordpress_db_name: "wordpress"
wordpress_db_user: "wpuser"
wordpress_db_password: "wppass"
domain_name: "blog.mapatacproxy.com"
email_certbot: "admin@mapatacloud.com"